package identity

import (
	"bytes"
	"encoding/base64"
	"encoding/json"
	"golang.org/x/crypto/curve25519"
	"os"
	"testing"
)

func TestSealDomains(t *testing.T) {
	pub, priv, err := GenerateX25519Keypair()
	if err != nil {
		t.Fatal(err)
	}
	for _, domain := range []string{MessageSealDomain, DriveSealDomain, DriveNameDomain, DriveRecordDomain} {
		t.Run(domain, func(t *testing.T) {
			context := []byte("node-key generation 1")
			if domain == MessageSealDomain {
				context = nil
			}
			payload, err := Seal(pub, []byte("secret"), domain, context)
			if err != nil {
				t.Fatal(err)
			}
			raw, err := OpenSeal(priv, payload, domain, context)
			if err != nil || string(raw) != "secret" {
				t.Fatalf("roundtrip %q %v", raw, err)
			}
			bad := payload
			bad.Nonce = ""
			if _, err := OpenSeal(priv, bad, domain, context); err == nil {
				t.Fatal("empty nonce accepted")
			}
			bad = payload
			bad.EphemeralPublicKey = base64.RawURLEncoding.EncodeToString(make([]byte, 32))
			if _, err := OpenSeal(priv, bad, domain, context); err == nil {
				t.Fatal("low-order key accepted")
			}
			bad = payload
			bad.Ciphertext = payload.Ciphertext[:4]
			if _, err := OpenSeal(priv, bad, domain, context); err == nil {
				t.Fatal("truncation accepted")
			}
			_, other, _ := GenerateX25519Keypair()
			if _, err := OpenSeal(other, payload, domain, context); err == nil {
				t.Fatal("wrong recipient accepted")
			}
			if domain != MessageSealDomain {
				if _, err := OpenSeal(priv, payload, domain, []byte("different node")); err == nil {
					t.Fatal("context substitution accepted")
				}
				if _, err := OpenSeal(priv, payload, MessageSealDomain, nil); err == nil {
					t.Fatal("drive payload accepted as message")
				}
				otherDomain := DriveNameDomain
				if domain == otherDomain {
					otherDomain = DriveSealDomain
				}
				if _, err := OpenSeal(priv, payload, otherDomain, context); err == nil {
					t.Fatal("cross-domain substitution accepted")
				}
			}
		})
	}
	for _, test := range []struct {
		domain  string
		context []byte
	}{{"unknown", nil}, {DriveSealDomain, nil}, {MessageSealDomain, []byte("extra")}} {
		if _, err := Seal(pub, nil, test.domain, test.context); err == nil {
			t.Fatal("invalid domain/context accepted")
		}
	}
	if _, err := Seal(pub[:31], nil, MessageSealDomain, nil); err == nil {
		t.Fatal("short public key accepted")
	}
	if _, err := OpenSeal(priv[:31], SealedPayload{}, MessageSealDomain, nil); err == nil {
		t.Fatal("short private key accepted")
	}
	if _, err := sealWithRandom(pub, nil, MessageSealDomain, nil, bytes.NewReader(nil)); err == nil {
		t.Fatal("entropy failure ignored")
	}
}

// A deterministic fixture uses throwaway entropy only inside the test. Public
// Seal always uses crypto/rand and does not accept caller-supplied nonces.
func TestVectors_DriveSeals(t *testing.T) {
	type vector struct {
		Domain    string        `json:"domain"`
		Private   string        `json:"private_key"`
		Public    string        `json:"public_key"`
		Context   string        `json:"context"`
		Plaintext string        `json:"plaintext"`
		Payload   SealedPayload `json:"payload"`
	}
	priv := bytes.Repeat([]byte{7}, 32)
	// Generate the matching public key via the existing derivation used by Seal.
	pub, err := curve25519.X25519(priv, curve25519.Basepoint)
	if err != nil {
		t.Fatal(err)
	}
	enc := base64.RawURLEncoding.EncodeToString
	var vectors []vector
	for _, domain := range []string{DriveSealDomain, DriveNameDomain, DriveRecordDomain, MessageSealDomain} {
		context := []byte("fixture context")
		if domain == MessageSealDomain {
			context = nil
		}
		payload, err := sealWithRandom(pub, []byte("drive secret"), domain, context, bytes.NewReader(bytes.Repeat([]byte{3}, 44)))
		if err != nil {
			t.Fatal(err)
		}
		vectors = append(vectors, vector{domain, enc(priv), enc(pub), enc(context), enc([]byte("drive secret")), payload})
	}
	raw, err := json.MarshalIndent(vectors, "", "  ")
	if err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile("testdata/vectors/drive-seals.json", append(raw, '\n'), 0644); err != nil {
		t.Fatal(err)
	}
}

// This fixture is frozen from before the extraction, not regenerated by TestVectors.
func TestSealMessageV1Compatibility(t *testing.T) {
	raw, err := os.ReadFile("testdata/message-seal-v1.json")
	if err != nil {
		t.Fatal(err)
	}
	var v struct {
		Private    string `json:"recipient_private_key"`
		Plaintext  string `json:"plaintext"`
		Ciphertext string `json:"ciphertext"`
		Ephemeral  string `json:"ephemeral_public_key"`
		Nonce      string `json:"nonce"`
	}
	if err := json.Unmarshal(raw, &v); err != nil {
		t.Fatal(err)
	}
	priv, err := base64.RawURLEncoding.DecodeString(v.Private)
	if err != nil {
		t.Fatal(err)
	}
	want, err := base64.RawURLEncoding.DecodeString(v.Plaintext)
	if err != nil {
		t.Fatal(err)
	}
	got, err := OpenSeal(priv, SealedPayload{v.Ciphertext, v.Ephemeral, v.Nonce}, MessageSealDomain, nil)
	if err != nil || !bytes.Equal(got, want) {
		t.Fatalf("v1 compatibility: %q %v", got, err)
	}
}
