import { themes as prismThemes } from 'prism-react-renderer';
import type { Config } from '@docusaurus/types';
import type * as Preset from '@docusaurus/preset-classic';

const siteUrl = process.env.SITE_URL || 'https://www.poweur.org';

const config: Config = {
  title: 'Poweur docs',
  tagline: 'Open-source ID, messaging and data sharing for an open internet',
  favicon: 'img/favicon.svg',

  // The docs live under the website at /docs. SITE_URL overrides the host
  url: siteUrl,
  baseUrl: '/docs/',

  organizationName: 'poweur',
  projectName: 'poweur',

  onBrokenLinks: 'warn',
  onBrokenMarkdownLinks: 'warn',

  i18n: {
    defaultLocale: 'en',
    locales: ['en'],
  },

  markdown: {
    mermaid: true,
  },

  themes: ['@docusaurus/theme-mermaid'],

  // Anonymous, first-party Faro telemetry (page views, errors, web vitals),
  // generated by packages/faro; same file as apps/site/assets/faro.js.
  // Script src is not prefixed with baseUrl, hence /docs/.
  scripts: [{ src: '/docs/js/faro.js', defer: true }],

  presets: [
    [
      'classic',
      {
        docs: {
          sidebarPath: './sidebars.ts',
          routeBasePath: '/',
          editUrl: 'https://github.com/romanmandryk/poweur/edit/master/apps/docs/',
        },
        blog: false,
        theme: {
          customCss: './src/css/custom.css',
        },
      } satisfies Preset.Options,
    ],
  ],

  themeConfig: {
    image: 'img/social-card.png',
    navbar: {
      title: 'Poweur docs',
      logo: {
        alt: 'Poweur ID Logo',
        src: 'img/logo.svg',
        srcDark: 'img/logo-dark.svg',
      },
      items: [
        {
          type: 'docSidebar',
          sidebarId: 'docsSidebar',
          position: 'left',
          label: 'Docs',
        },
        {
          to: '/relay/api-reference',
          label: 'API Reference',
          position: 'left',
        },
        {
          label: 'Get Started',
          to: '/',
          position: 'right',
          className: 'navbar__item--cta',
        },
        {
          // The website itself, on the same host.
          href: `${siteUrl}/`,
          target: '_self',
          label: 'poweur.org',
          position: 'right',
        },
        {
          href: 'https://github.com/romanmandryk/poweur',
          label: 'GitHub',
          position: 'right',
        },
      ],
    },
    footer: {
      style: 'dark',
      links: [
        {
          title: 'Protocol',
          items: [
            { label: 'Introduction', to: '/' },
            { label: 'Protocol Overview', to: '/protocol/overview' },
            { label: 'Identity Model', to: '/protocol/identity-model' },
            { label: 'DNS Records', to: '/protocol/dns-records' },
          ],
        },
        {
          title: 'Relay',
          items: [
            { label: 'Self-hosting', to: '/relay/self-hosting' },
            { label: 'Relay Overview', to: '/relay/overview' },
            { label: 'API Reference', to: '/relay/api-reference' },
            { label: 'Configuration', to: '/relay/configuration' },
          ],
        },
        {
          title: 'More',
          items: [
            { label: 'Security Model', to: '/security/model' },
            { label: 'Future Capabilities', to: '/future/capabilities' },
            { label: 'GitHub', href: 'https://github.com/romanmandryk/poweur' },
          ],
        },
      ],
      copyright: `Copyright © ${new Date().getFullYear()} Poweur ID. Built with Docusaurus.`,
    },
    prism: {
      theme: prismThemes.github,
      darkTheme: prismThemes.dracula,
      additionalLanguages: ['bash', 'json', 'toml', 'dns-zone-file'],
    },
    mermaid: {
      theme: { light: 'neutral', dark: 'dark' },
    },
  } satisfies Preset.ThemeConfig,
};

export default config;
