apiVersion: 1
datasources:
  - name: Prometheus
    uid: prometheus
    orgId: 1
    type: prometheus
    access: proxy
    url: http://infra-prometheus:9090
    isDefault: true
    editable: false
  - name: Loki
    uid: loki
    orgId: 1
    type: loki
    access: proxy
    url: http://infra-loki:3100
    editable: false
