/**
 * The install surface (E15-T14): favicon, touch icon and web manifest. They are
 * generated by design/brand/scripts/icons.py; these tests catch a lost file, a
 * wrong size, or a root-relative path that would 404 inside the Capacitor shell.
 */
import { describe, expect, it } from "vitest";
import { existsSync, readFileSync } from "node:fs";
import { join } from "node:path";

const WEB = join(import.meta.dirname, "..");
const PUBLIC = join(WEB, "public");

/** Width and height from a PNG's IHDR chunk. */
function pngSize(path: string): [number, number] {
  const bytes = readFileSync(path);
  expect(bytes.subarray(1, 4).toString("latin1")).toBe("PNG");
  return [bytes.readUInt32BE(16), bytes.readUInt32BE(20)];
}

describe("brand assets", () => {
  const html = readFileSync(join(WEB, "index.html"), "utf8");
  const links = [...html.matchAll(/<link rel="(icon|apple-touch-icon|manifest)" href="([^"]+)"/g)].map((m) => [m[1], m[2]]);

  it("index.html links a favicon (ico + svg), a touch icon and the manifest", () => {
    expect(links).toEqual([
      ["icon", "/favicon.ico"],
      ["icon", "/favicon.svg"],
      ["apple-touch-icon", "/apple-touch-icon.png"],
      ["manifest", "/manifest.webmanifest"],
    ]);
    // Root paths are only safe because they name public/ files, which Vite
    // rewrites against base "./"; anything else would stay absolute.
    for (const [, href] of links) expect(existsSync(join(PUBLIC, href))).toBe(true);
  });

  it("ships the touch icon at 180 px", () => {
    expect(pngSize(join(PUBLIC, "apple-touch-icon.png"))).toEqual([180, 180]);
  });

  it("the manifest's icons exist at the sizes it declares, relative to the app", () => {
    const manifest = JSON.parse(readFileSync(join(PUBLIC, "manifest.webmanifest"), "utf8"));
    expect(manifest).toMatchObject({ name: "Poweur ID", short_name: "Poweur", start_url: ".", scope: ".", display: "standalone" });
    expect(manifest.icons.some((icon: { purpose: string }) => icon.purpose === "maskable")).toBe(true);
    for (const icon of manifest.icons) {
      expect(icon.src).not.toMatch(/^\//);
      const path = join(PUBLIC, icon.src);
      expect(existsSync(path)).toBe(true);
      if (icon.type === "image/png") {
        const [w, h] = icon.sizes.split("x").map(Number);
        expect(pngSize(path)).toEqual([w, h]);
      }
    }
  });
});
