/**
 * Canonical signing strings — the byte-exact twins of
 * `apps/api/internal/crypto/signing.go` and `packages/identity/grants.go`.
 *
 * Go stays canonical: every function here is pinned by the conformance
 * vectors in `test/conformance.test.ts`, generated by
 * `packages/identity/vectors_test.go`. Change a string in Go without
 * changing it here and CI goes red.
 */

import type { EncryptionMeta, ShareAudience } from "./types.js";

/**
 * Message signing input (crypto.CanonicalMessageTyped). Optional lines are
 * appended only when the field is non-empty, in this fixed order:
 * id, session, enc, type.
 */
export function canonicalMessage(input: {
  sender: string;
  recipient: string;
  timestamp: string;
  payload: string;
  id?: string;
  sessionId?: string;
  encryption?: EncryptionMeta | null;
  type?: string;
}): string {
  const parts = [input.sender, input.recipient, input.timestamp, input.payload];
  if (input.id) parts.push(`id:${input.id}`);
  if (input.sessionId) parts.push(`session:${input.sessionId}`);
  if (input.encryption?.alg) {
    parts.push(
      `enc:${input.encryption.alg}:${input.encryption.ephemeral_public_key}:${input.encryption.nonce}`,
    );
  }
  if (input.type) parts.push(`type:${input.type}`);
  return parts.join("\n");
}

/** Delivery-ack signing input (crypto.CanonicalAck). */
export function canonicalAck(input: {
  id: string;
  messageId: string;
  state: string;
  sender: string;
  recipient: string;
  timestamp: string;
  sessionId?: string;
}): string {
  const parts = [
    "ack",
    input.id,
    input.messageId,
    input.state,
    input.sender,
    input.recipient,
    input.timestamp,
  ];
  if (input.sessionId) parts.push(`session:${input.sessionId}`);
  return parts.join("\n");
}

/** POST /identities owner proof (crypto.CanonicalIdentityRegistration). */
export function canonicalIdentityRegistration(
  identity: string,
  publicKey: string,
  encryptionPublicKey: string,
  relayAddress: string,
  issuedAt: string,
  nonce: string,
): string {
  return [
    "identity-registration",
    identity,
    publicKey,
    encryptionPublicKey,
    relayAddress,
    issuedAt,
    nonce,
  ].join("\n");
}

/** POST /identities/{id}/export (crypto.CanonicalIdentityExport). */
export function canonicalIdentityExport(identity: string, issuedAt: string, nonce: string): string {
  return ["identity-export", identity, issuedAt, nonce].join("\n");
}

/**
 * POST /identities/{id}/rotate (crypto.CanonicalIdentityRotation) — signed by
 * the *old* key so the relay can chain trust across the change.
 */
export function canonicalIdentityRotation(
  identity: string,
  oldPublicKey: string,
  newPublicKey: string,
  issuedAt: string,
  nonce: string,
): string {
  return ["identity-rotation", identity, oldPublicKey, newPublicKey, issuedAt, nonce].join("\n");
}

/** POST /identities/{id}/encryption-key (crypto.CanonicalEncryptionKeyUpdate). */
export function canonicalEncryptionKeyUpdate(
  identity: string,
  encryptionPublicKey: string,
  issuedAt: string,
  nonce: string,
): string {
  return ["identity-encryption-key", identity, encryptionPublicKey, issuedAt, nonce].join("\n");
}

/** POST /auth/dav-token (crypto.CanonicalDAVToken). */
export function canonicalDavToken(
  identity: string,
  audience: string,
  scope: string,
  issuedAt: string,
  nonce: string,
): string {
  return ["dav-token", identity, audience, scope, issuedAt, nonce].join("\n");
}

/** POST /sessions (crypto.CanonicalSessionRegistration). */
export function canonicalSessionRegistration(
  identity: string,
  sessionPublicKey: string,
  issuedAt: string,
  expiresAt: string,
  nonce: string,
): string {
  return [
    "session-registration",
    identity,
    sessionPublicKey,
    issuedAt,
    expiresAt,
    nonce,
  ].join("\n");
}

/** DELETE /sessions/{id} (crypto.CanonicalSessionRevocation). */
export function canonicalSessionRevocation(
  identity: string,
  sessionId: string,
  issuedAt: string,
  nonce: string,
): string {
  return ["session-revocation", identity, sessionId, issuedAt, nonce].join("\n");
}

/**
 * Share-grant audience rendering (identity.canonicalAudience): each entry
 * becomes `id:<lowercased>` or `group:<lowercased>`, sorted, comma-joined.
 */
export function canonicalAudience(audience: ShareAudience[]): string {
  const parts = audience.map((entry) =>
    entry.id ? `id:${entry.id.trim().toLowerCase()}` : `group:${(entry.group ?? "").trim().toLowerCase()}`,
  );
  parts.sort();
  return parts.join(",");
}

/** Share-grant signing input (ShareGrant.Canonical). */
export function canonicalShareGrant(grant: {
  share_id: string;
  owner: string;
  path: string;
  audience: ShareAudience[];
  permissions: string[];
  created_at?: string;
  expires_at?: string;
}): string {
  const permissions = [...grant.permissions].sort();
  return [
    "poweur-share-grant",
    grant.share_id.trim(),
    grant.owner.trim().toLowerCase(),
    normalizeGrantPath(grant.path),
    canonicalAudience(grant.audience),
    permissions.join(","),
    grant.created_at ?? "",
    grant.expires_at ?? "",
  ].join("\n");
}

/** Share-group signing input (ShareGroup.Canonical). */
export function canonicalShareGroup(group: {
  group: string;
  owner: string;
  // A group with no members serializes as `null` from Go's nil slice, so an
  // empty group must canonicalize the same on both sides.
  members: string[] | null | undefined;
  updated_at?: string;
}): string {
  const members = (group.members ?? []).map((m) => m.trim().toLowerCase()).sort();
  return [
    "poweur-share-group",
    group.group.trim().toLowerCase(),
    group.owner.trim().toLowerCase(),
    members.join(","),
    group.updated_at ?? "",
  ].join("\n");
}

/** Tree roots a grant may cover (identity.ShareRoots). */
export const SHARE_ROOTS = ["shared", "apps"] as const;

/**
 * Validate and normalize a grant path (identity.NormalizeGrantPath). Throws
 * on anything outside a shareable root, or on the root itself.
 *
 * Kept here rather than in shares.ts because the canonical string depends on
 * it — signing a non-normalized path would produce a grant the relay rejects.
 */
export function normalizeGrantPath(raw: string): string {
  const path = raw.trim().replace(/^\/+/, "").replace(/\/+$/, "");
  if (path === "") throw new Error("grant path is empty");
  for (const segment of path.split("/")) {
    if (segment === "" || segment === "." || segment === "..") {
      throw new Error(`invalid grant path segment "${segment}"`);
    }
  }
  const slash = path.indexOf("/");
  const top = slash >= 0 ? path.slice(0, slash) : path;
  for (const root of SHARE_ROOTS) {
    if (top === root) {
      if (path === root) {
        throw new Error(`cannot grant the ${root} root itself; share a subfolder or file`);
      }
      return path;
    }
  }
  throw new Error(`grants may only cover paths under /${SHARE_ROOTS.join("/ or /")}`);
}

/**
 * Deterministic JSON for identity documents (identity.marshalCanonical):
 * object keys sorted, no whitespace, no signature field, omitted empties.
 */
export function marshalCanonicalJSON(value: unknown): string {
  if (value === null || typeof value !== "object") return JSON.stringify(value);
  if (Array.isArray(value)) {
    return `[${value.map(marshalCanonicalJSON).join(",")}]`;
  }
  const record = value as Record<string, unknown>;
  const keys = Object.keys(record).filter((k) => record[k] !== undefined).sort();
  const body = keys.map((k) => `${JSON.stringify(k)}:${marshalCanonicalJSON(record[k])}`);
  return `{${body.join(",")}}`;
}
