/**
 * Canonical signing strings — the byte-exact twins of
 * `apps/api/internal/crypto/signing.go` and `packages/identity/grants.go`.
 *
 * Go stays canonical: every function here is pinned by the conformance
 * vectors in `test/conformance.test.ts`, generated by
 * `packages/identity/vectors_test.go`. Change a string in Go without
 * changing it here and CI goes red.
 */

import { metadataLines } from "./msgtypes.js";
import type { EncryptionMeta } from "./types.js";

/**
 * Message signing input (`crypto.CanonicalMessageEnvelope` in Go). Optional
 * lines are appended only when the field is non-empty, in this fixed order:
 *
 * ```
 * <sender>
 * <recipient>
 * <timestamp>
 * <payload>
 * id:<id>                          // when id is set
 * session:<session_id>             // when sessionId is set
 * enc:<alg>:<eph>:<nonce>          // when encryption is set
 * type:<type>                      // when type is set
 * thread:<thread_id>               // when threadId is set
 * expires:<expires_at>             // when expiresAt is set
 * meta:<key>:<value>               // one line per entry, keys ascending
 * ```
 *
 * The append-only rule is the whole compatibility story. A client that sets
 * none of the newer fields produces the byte-identical string every previous
 * protocol revision produced, so an old relay verifies a new client and a new
 * relay verifies an old one. Never insert a line between the existing ones.
 *
 * Metadata is a flat map of printable strings (see `msgtypes.ts`): keys are
 * ASCII, so JavaScript's sort and Go's byte-wise sort agree, and values carry
 * no control characters, so `meta:` lines need no escaping.
 */
export function canonicalMessage(input: {
  sender: string;
  recipient: string;
  timestamp: string;
  payload: string;
  id?: string;
  sessionId?: string;
  encryption?: EncryptionMeta | null;
  type?: string;
  threadId?: string;
  expiresAt?: string;
  metadata?: Record<string, string>;
}): string {
  const parts = [input.sender, input.recipient, input.timestamp, input.payload];
  if (input.id) parts.push(`id:${input.id}`);
  if (input.sessionId) parts.push(`session:${input.sessionId}`);
  if (input.encryption?.alg) {
    parts.push(
      `enc:${input.encryption.alg}:${input.encryption.ephemeral_public_key}:${input.encryption.nonce}`,
    );
  }
  if (input.type) parts.push(`type:${input.type}`);
  if (input.threadId) parts.push(`thread:${input.threadId}`);
  if (input.expiresAt) parts.push(`expires:${input.expiresAt}`);
  parts.push(...metadataLines(input.metadata));
  return parts.join("\n");
}

/** Delivery-ack signing input (crypto.CanonicalAck). */
export function canonicalAck(input: {
  id: string;
  messageId: string;
  state: string;
  sender: string;
  recipient: string;
  timestamp: string;
  sessionId?: string;
}): string {
  const parts = [
    "ack",
    input.id,
    input.messageId,
    input.state,
    input.sender,
    input.recipient,
    input.timestamp,
  ];
  if (input.sessionId) parts.push(`session:${input.sessionId}`);
  return parts.join("\n");
}

/** POST /identities owner proof (crypto.CanonicalIdentityRegistration). */
export function canonicalIdentityRegistration(
  identity: string,
  publicKey: string,
  encryptionPublicKey: string,
  relayAddress: string,
  issuedAt: string,
  nonce: string,
): string {
  return [
    "identity-registration",
    identity,
    publicKey,
    encryptionPublicKey,
    relayAddress,
    issuedAt,
    nonce,
  ].join("\n");
}

/** POST /identities/{id}/export (crypto.CanonicalIdentityExport). */
export function canonicalIdentityExport(identity: string, issuedAt: string, nonce: string): string {
  return ["identity-export", identity, issuedAt, nonce].join("\n");
}

/**
 * POST /identities/{id}/rotate (crypto.CanonicalIdentityRotation) — signed by
 * the *old* key so the relay can chain trust across the change.
 */
export function canonicalIdentityRotation(
  identity: string,
  oldPublicKey: string,
  newPublicKey: string,
  issuedAt: string,
  nonce: string,
): string {
  return ["identity-rotation", identity, oldPublicKey, newPublicKey, issuedAt, nonce].join("\n");
}

/** POST /sessions (crypto.CanonicalSessionRegistration). */
export function canonicalSessionRegistration(
  identity: string,
  sessionPublicKey: string,
  issuedAt: string,
  expiresAt: string,
  nonce: string,
): string {
  return [
    "session-registration",
    identity,
    sessionPublicKey,
    issuedAt,
    expiresAt,
    nonce,
  ].join("\n");
}

/** DELETE /sessions/{id} (crypto.CanonicalSessionRevocation). */
export function canonicalSessionRevocation(
  identity: string,
  sessionId: string,
  issuedAt: string,
  nonce: string,
): string {
  return ["session-revocation", identity, sessionId, issuedAt, nonce].join("\n");
}

/**
 * Share-group signing input (ShareGroup.Canonical).
 *
 * A group *identity* (E05-T5) appends three more lines — the marker, the
 * sorted admin list and the membership epoch. A group with no admins signs
 * exactly the five lines it always did, so introducing group identities
 * invalidated no existing owner-local group signature.
 */
export function canonicalShareGroup(group: {
  group: string;
  owner: string;
  // A group with no members serializes as `null` from Go's nil slice, so an
  // empty group must canonicalize the same on both sides.
  members: string[] | null | undefined;
  admins?: string[] | null;
  epoch?: number;
  updated_at?: string;
}): string {
  const members = (group.members ?? []).map((m) => m.trim().toLowerCase()).sort();
  const fields = [
    "poweur-share-group",
    group.group.trim().toLowerCase(),
    group.owner.trim().toLowerCase(),
    members.join(","),
    group.updated_at ?? "",
  ];
  if (group.admins?.length) {
    const admins = group.admins.map((a) => a.trim().toLowerCase()).sort();
    fields.push("poweur-group-identity", admins.join(","), String(group.epoch ?? 0));
  }
  return fields.join("\n");
}

/** Where a group identity keeps its own membership (identity.GroupSelfDoc). */
export const GROUP_SELF_DOC = ".poweur/relay/group.json";

/**
 * Does this group name refer to an addressable group *identity* rather than
 * an owner-local group? The rule is the presence of
 * a dot: a Poweur ID is a domain name and always has one, and owner-local
 * group names are forbidden from having one.
 */
export function isGroupIdentityName(name: string): boolean {
  return name.trim().includes(".");
}

/**
 * Deterministic JSON for identity documents (identity.marshalCanonical):
 * object keys sorted, no whitespace, no signature field, omitted empties.
 */
export function marshalCanonicalJSON(value: unknown): string {
  if (value === null || typeof value !== "object") return JSON.stringify(value);
  if (Array.isArray(value)) {
    return `[${value.map(marshalCanonicalJSON).join(",")}]`;
  }
  const record = value as Record<string, unknown>;
  const keys = Object.keys(record).filter((k) => record[k] !== undefined).sort();
  const body = keys.map((k) => `${JSON.stringify(k)}:${marshalCanonicalJSON(record[k])}`);
  return `{${body.join(",")}}`;
}

/** PUT /identities/{id}/keystore (crypto.CanonicalKeystoreEnroll). */
export function canonicalKeystoreEnroll(
  identity: string,
  enrollmentId: string,
  kind: string,
  credentialId: string,
  wrappedDigest: string,
  issuedAt: string,
  nonce: string,
): string {
  return [
    "keystore-enroll",
    identity,
    enrollmentId,
    kind,
    credentialId,
    wrappedDigest,
    issuedAt,
    nonce,
  ].join("\n");
}

/**
 * POST /identities/{id}/keystore/list (crypto.CanonicalKeystoreList).
 *
 * Metadata only: an owner enumerating their own devices has no need for the
 * wrapped ciphertext, so this read is identity-signed rather than gated on a
 * WebAuthn assertion the way `fetch` is.
 */
export function canonicalKeystoreList(
  identity: string,
  issuedAt: string,
  nonce: string,
): string {
  return ["keystore-list", identity, issuedAt, nonce].join("\n");
}

/** DELETE /identities/{id}/keystore/{enrollment} (crypto.CanonicalKeystoreRemove). */
export function canonicalKeystoreRemove(
  identity: string,
  enrollmentId: string,
  issuedAt: string,
  nonce: string,
): string {
  return ["keystore-remove", identity, enrollmentId, issuedAt, nonce].join("\n");
}

/**
 * Device-enrollment rendezvous actions (crypto.CanonicalEnrollAction).
 * `action` is "enroll-fetch" or "enroll-deliver"; the rendezvous id is bound
 * in so an approval cannot be redirected to a different offer.
 */
export function canonicalEnrollAction(
  action: string,
  identity: string,
  rendezvousId: string,
  issuedAt: string,
  nonce: string,
): string {
  return [action, identity, rendezvousId, issuedAt, nonce].join("\n");
}
